#include "core/export/IdaExporter.h"

#include <sstream>

#include "util/FileIO.h"

namespace flutterdec::core::exporting {

util::Status export_ida(const model::Program& program, const std::string& out_py) {
  std::ostringstream py;
  py << "# Auto-generated by flutterdec\n";
  py << "import ida_name\n\n";
  for (const auto& fn : program.functions) {
    py << "ida_name.set_name(0x" << std::hex << fn.entry_va << std::dec << ", \""
       << fn.owner_class_display << "__" << fn.name_display << "\", ida_name.SN_NOWARN)\n";
  }
  return util::WriteFile(out_py, py.str());
}

}  // namespace flutterdec::core::exporting
