[package]
name = "flutterdec-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
sha2.workspace = true
flutterdec-loader = { path = "../flutterdec-loader" }
